# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Workledger < Formula
  desc "Local-first CLI for managing canonical worklogs"
  homepage "https://github.com/solitus0/workledger"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/solitus0/workledger/releases/download/v0.1.3/workledger_0.1.3_darwin_amd64.tar.gz"
      sha256 "f3a6e178b3a34386adfcf08932cb4d197525c2c7a6d99402612dfede2749de8d"

      define_method(:install) do
        bin.install "workledger"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/solitus0/workledger/releases/download/v0.1.3/workledger_0.1.3_darwin_arm64.tar.gz"
      sha256 "e290fa972896d8eba01d3d899dcd3640873abd9ad162fe543fbc45e4410c077b"

      define_method(:install) do
        bin.install "workledger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/solitus0/workledger/releases/download/v0.1.3/workledger_0.1.3_linux_amd64.tar.gz"
      sha256 "fbcfcda768f20879b560c6abcd4a220c15aa9ea73b42ff82bbd901845e27d757"
      define_method(:install) do
        bin.install "workledger"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/solitus0/workledger/releases/download/v0.1.3/workledger_0.1.3_linux_arm64.tar.gz"
      sha256 "5190579fafcd1a70092af30aa6477087eda12ee34d1160085d23a42fb201d22e"
      define_method(:install) do
        bin.install "workledger"
      end
    end
  end

  test do
    system "#{bin}/workledger", "--version"
  end
end
