# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Workledger < Formula
  desc "Local-first CLI for managing canonical worklogs"
  homepage "https://github.com/solitus0/workledger"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/solitus0/workledger/releases/download/v0.1.0/workledger_0.1.0_darwin_amd64.tar.gz"
      sha256 "ee57a8a9f2a77155b56f4759f7e484193e0051118c5b10b05fa908e061265fde"

      define_method(:install) do
        bin.install "workledger"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/solitus0/workledger/releases/download/v0.1.0/workledger_0.1.0_darwin_arm64.tar.gz"
      sha256 "9043c795fc6f3aff2f77d89c59bd03108c3204cf9cb20a1d9599b02eb8213887"

      define_method(:install) do
        bin.install "workledger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/solitus0/workledger/releases/download/v0.1.0/workledger_0.1.0_linux_amd64.tar.gz"
      sha256 "8e5aa6f5cb07927c7e80dcf10ca3fc3cee0f7ae5ab41068e3d14e23658a8b99f"
      define_method(:install) do
        bin.install "workledger"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/solitus0/workledger/releases/download/v0.1.0/workledger_0.1.0_linux_arm64.tar.gz"
      sha256 "8d7576015719275a4fdad6bc2a04ec6121512e5f217ef7dcf991c5f8b4124fa9"
      define_method(:install) do
        bin.install "workledger"
      end
    end
  end

  test do
    system "#{bin}/workledger", "--version"
  end
end
